name: build

run-name: Build Project

on: [push]

env:
  AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build

  source-bundle:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
      - run: npm run build

  docker-build:
    runs-on: ubuntu-latest
    needs: source-bundle
    steps:
      - run: docker build -t nginx-test .
  docker-push:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - run: echo $AUTH_TOKEN
